// Code generated by Kitex v0.9.1. DO NOT EDIT.

package bizservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	gateway "student/kitex_gen/gateway"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newBizServiceRegisterArgs,
		newBizServiceRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Query": kitex.NewMethodInfo(
		queryHandler,
		newBizServiceQueryArgs,
		newBizServiceQueryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	bizServiceServiceInfo                = NewServiceInfo()
	bizServiceServiceInfoForClient       = NewServiceInfoForClient()
	bizServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return bizServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return bizServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return bizServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "BizService"
	handlerType := (*gateway.BizService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "gateway",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*gateway.BizServiceRegisterArgs)
	realResult := result.(*gateway.BizServiceRegisterResult)
	success, err := handler.(gateway.BizService).Register(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBizServiceRegisterArgs() interface{} {
	return gateway.NewBizServiceRegisterArgs()
}

func newBizServiceRegisterResult() interface{} {
	return gateway.NewBizServiceRegisterResult()
}

func queryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*gateway.BizServiceQueryArgs)
	realResult := result.(*gateway.BizServiceQueryResult)
	success, err := handler.(gateway.BizService).Query(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newBizServiceQueryArgs() interface{} {
	return gateway.NewBizServiceQueryArgs()
}

func newBizServiceQueryResult() interface{} {
	return gateway.NewBizServiceQueryResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Register(ctx context.Context, req *gateway.BizRequest) (r *gateway.BizResponse, err error) {
	var _args gateway.BizServiceRegisterArgs
	_args.Req = req
	var _result gateway.BizServiceRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Query(ctx context.Context, req *gateway.BizRequest) (r *gateway.BizResponse, err error) {
	var _args gateway.BizServiceQueryArgs
	_args.Req = req
	var _result gateway.BizServiceQueryResult
	if err = p.c.Call(ctx, "Query", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
