// Code generated by Kitex v0.9.1. DO NOT EDIT.

package bizservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	gateway "student/kitex_gen/gateway"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Register(ctx context.Context, req *gateway.BizRequest, callOptions ...callopt.Option) (r *gateway.BizResponse, err error)
	Query(ctx context.Context, req *gateway.BizRequest, callOptions ...callopt.Option) (r *gateway.BizResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kBizServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kBizServiceClient struct {
	*kClient
}

func (p *kBizServiceClient) Register(ctx context.Context, req *gateway.BizRequest, callOptions ...callopt.Option) (r *gateway.BizResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, req)
}

func (p *kBizServiceClient) Query(ctx context.Context, req *gateway.BizRequest, callOptions ...callopt.Option) (r *gateway.BizResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Query(ctx, req)
}
